---
newt_client_id: "{{ newt_pi_client_id }}"
newt_client_secret: "{{ newt_pi_client_secret }}"

photoprism_backup_enabled: true
photoprism_backup_borgmatic_target: "rclone:backup:{{ backup_s3_bucket_name }}/photoprism"
photoprism_backup_borgmatic_password: "{{ backup_passphrase }}"

immich_backup_enabled: true
immich_domain: "immich.sylvain.cloud"
immich_backup_borgmatic_target: "rclone:backup:{{ backup_s3_bucket_name }}/immich"
immich_backup_borgmatic_password: "{{ backup_passphrase }}"
immich_backup_healthcheck_url: ""
