---
services:
  newt:
    image: fosrl/newt:1.9.0@sha256:22edec551d81c500a9a3c790a41cd8f7eada3b47ba0a31a187c80d61318e4cc6
    container_name: newt
    restart: unless-stopped
    environment:
      - PANGOLIN_ENDPOINT={{ newt_endpoint }}
      - NEWT_ID={{ newt_client_id }}
      - NEWT_SECRET={{ newt_client_secret }}
      - DOCKER_SOCKET=unix:///var/run/docker.sock
      - DOCKER_ENFORCE_NETWORK_VALIDATION=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - newt

networks:
  newt:
    name: newt
    driver: bridge
