---
monica_v4_base_path: "{{ docker_base_path }}/monica_v4"
monica_v4_domain: crm.sylvain.dev
monica_v4_db_password: ""
monica_v4_healthcheck_url: ""
monica_v4_cron_healthcheck_url: ""

# Borgmatic backup configuration
monica_v4_backup_enabled: true
monica_v4_backup_borgmatic_target: ""
monica_v4_backup_encryption_passphrase: ""
monica_v4_backup_healthcheck_url: ""
