---
wiki_base_path: "{{ docker_base_path }}/wiki"
wiki_domain: "wiki.sylvain.cloud"
wiki_db_password: "wiki"
wiki_backup_enabled: true
wiki_backup_borgmatic_target: ""
wiki_backup_borgmatic_password: ""
wiki_backup_healthcheck_url: ""
