---
nextcloud_base_path: "{{ docker_base_path }}/nextcloud"
nextcloud_domain: sylvain.cloud
nextcloud_db_password: "nextcloud"
nextcloud_redis_password: "redis"

# Backup (borgmatic)
nextcloud_backup_enabled: true
nextcloud_backup_borgmatic_target: ""
nextcloud_backup_borgmatic_password: ""
nextcloud_backup_healthcheck_url: ""
