#
# WARNING: To install Immich, follow our guide: https://docs.immich.app/install/docker-compose
#
# Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
name: immich
services:
  immich-server:
    labels:
      - pangolin.public-resources.immich.name=Immich
      - pangolin.public-resources.immich.full-domain={{ immich_domain }}
      - pangolin.public-resources.immich.auth.pincode={{ immich_pin }}
      - pangolin.public-resources.immich.protocol=http
      - pangolin.public-resources.immich.targets[0].method=http
      - pangolin.public-resources.immich.targets[0].port=2283
      - pangolin.public-resources.immich.auth.sso-enabled=true
      - pangolin.public-resources.immich.auth.sso-roles[0]=Immich
      - pangolin.public-resources.immich.healthcheck.hostname=immich
      - pangolin.public-resources.immich.healthcheck.port=2283
      - pangolin.public-resources.immich.healthcheck.enabled=true
      - pangolin.public-resources.immich.healthcheck.path=/
      - pangolin.public-resources.immich.healthcheck.interval=30
      - pangolin.public-resources.immich.healthcheck.timeout=5
      - pangolin.public-resources.immich.healthcheck.method=GET
      - pangolin.public-resources.immich.healthcheck.status=200
      - pangolin.public-resources.immich.rules[0].action=allow
      - pangolin.public-resources.immich.rules[0].match=ip
      - pangolin.public-resources.immich.rules[0].value=176.129.132.36
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:v2.5.2@sha256:8ac5a6d471fbb6fcfec6bc34854dd5a947c1795547f0d9345d9bf1803d1209e3
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
      - ${UPLOAD_LOCATION}:/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    ports:
      - '2283:2283'
    depends_on:
      - redis
      - database
    networks:
      - newt
      - immich
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:v2.5.2@sha256:531d2bccbe20d0412496e36455715a18d692911eca5e2ee37d32e1e4f50e14bb
    # extends: # uncomment this section for hardware acceleration - see https://docs.immich.app/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    env_file:
      - .env
    networks:
      - immich
    restart: always
    healthcheck:
      disable: false

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:9@sha256:546304417feac0874c3dd576e0952c6bb8f06bb4093ea0c9ca303c73cf458f63
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always
    ports:
      - 6379:6379
    networks:
      - immich

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # Uncomment the DB_STORAGE_TYPE: 'HDD' var if your database isn't stored on SSDs
      #DB_STORAGE_TYPE: 'HDD'
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    shm_size: 128mb
    ports:
      - 5432:5432
    restart: always
    networks:
      - immich

  # No ARM support :(
  # immich-swipe:
  #   labels:
  #     - pangolin.public-resources.immich.name=Immich Swipe
  #     - pangolin.public-resources.immich.full-domain=swipe-{{ immich_domain }}
  #     # - pangolin.public-resources.immich.auth.pincode={{ immich_pin }}
  #     - pangolin.public-resources.immich.protocol=http
  #     - pangolin.public-resources.immich.targets[0].method=http
  #     - pangolin.public-resources.immich.targets[0].port=80
  #     - pangolin.public-resources.immich.auth.sso-enabled=true
  #     - pangolin.public-resources.immich.auth.sso-roles[0]=Immich
  #     - pangolin.public-resources.immich.healthcheck.hostname=immich-swipe
  #     - pangolin.public-resources.immich.healthcheck.port=80
  #     - pangolin.public-resources.immich.healthcheck.enabled=true
  #     - pangolin.public-resources.immich.healthcheck.path=/
  #     - pangolin.public-resources.immich.healthcheck.interval=30
  #     - pangolin.public-resources.immich.healthcheck.timeout=5
  #     - pangolin.public-resources.immich.healthcheck.method=GET
  #     - pangolin.public-resources.immich.healthcheck.status=200
  #     # - pangolin.public-resources.immich.rules[0].action=allow
  #     # - pangolin.public-resources.immich.rules[0].match=ip
  #     # - pangolin.public-resources.immich.rules[0].value=176.129.132.36
  #   image: ghcr.io/dev-nick421/immich-swipe:sha-a487c3e
  #   container_name: immich-swipe

volumes:
  model-cache:

networks:
  immich:
  newt:
    external: true
