---
- name: Ensure base and config directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
  loop:
    - "{{ spliit_base_path }}"
    - "{{ spliit_base_path }}/db_data"

- name: Template compose configuration
  ansible.builtin.template:
    src: "compose.yaml"
    dest: "{{ spliit_base_path }}/compose.yaml"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
    mode: "0644"
  notify: Restart spliit service

- name: Template environment file
  notify: Restart spliit service
  ansible.builtin.template:
    src: ".env.j2"
    dest: "{{ spliit_base_path }}/.env"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
    mode: "0640"

- name: Ensure spliit systemd user service is running
  ansible.builtin.systemd:
    name: dc@spliit
    scope: user
    state: started
    enabled: true
    daemon_reload: true

- name: Configure borgmatic backup for spliit
  when: spliit_backup_enabled
  tags: backup
  block:
    - name: Create borgmatic configuration for spliit
      become: true
      ansible.builtin.template:
        src: "borgmatic-spliit.yaml.j2"
        dest: "{{ borgmatic_config_dir }}/spliit.yaml"
        owner: root
        group: root
        mode: '0600'

    - name: Initialize borg repository for spliit
      become: true
      ansible.builtin.shell:
        cmd: "/root/.local/bin/borgmatic --config {{ borgmatic_config_dir }}/spliit.yaml repo-create --encryption {{ borgmatic_encryption_mode | default('repokey-aes-ocb') }}"
      register: borg_repo_create
      changed_when: "'repository already exists' not in borg_repo_create.stderr"
      failed_when: >
        borg_repo_create.rc != 0 and
        'repository already exists' not in borg_repo_create.stderr
