---
- name: Create Pangolin directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ pangolin_dir }}"
    - "{{ pangolin_dir }}/config"
    - "{{ pangolin_dir }}/config/traefik"
    - "{{ pangolin_dir }}/config/traefik/logs"
    - "{{ pangolin_dir }}/config/letsencrypt"

- name: Download GeoLite2-Country database
  become: true
  ansible.builtin.get_url:
    url: https://git.io/GeoLite2-Country.mmdb
    dest: "{{ pangolin_dir }}/config/GeoLite2-Country.mmdb"
    mode: "0644"
    owner: root
    group: root
  when: deploy_pangolin_config | bool

- name: Create Traefik dynamic configuration
  become: true
  ansible.builtin.template:
    src: traefik_dynamic_config.yml.j2
    dest: "{{ pangolin_dir }}/config/traefik/dynamic_config.yml"
    mode: "0644"
    owner: root
    group: root
  when: deploy_pangolin_config | bool

- name: Create Traefik configuration
  become: true
  notify: Restart Pangolin service
  ansible.builtin.template:
    src: traefik_config.yml.j2
    dest: "{{ pangolin_dir }}/config/traefik/traefik_config.yml"
    mode: "0644"
    owner: root
    group: root
  when: deploy_pangolin_config | bool

- name: Create Pangolin configuration
  become: true
  notify: Restart Pangolin service
  ansible.builtin.template:
    src: pangolin_config.yml.j2
    dest: "{{ pangolin_dir }}/config/config.yml"
    mode: "0600"
    owner: root
    group: root
  when: deploy_pangolin_config | bool

- name: Create compose.yml
  notify: Restart Pangolin service
  ansible.builtin.template:
    src: compose.yaml
    dest: "{{ pangolin_dir }}/compose.yaml"
    mode: "0644"

- name: Create Pangolin systemd service
  ansible.builtin.template:
    src: pangolin.service.j2
    dest: /etc/systemd/system/pangolin.service
    mode: "0644"

- name: Enable Pangolin service
  ansible.builtin.systemd:
    name: pangolin
    enabled: true
    state: started
    daemon_reload: true
  when: deploy_pangolin_config | bool
