---
- name: Ensure Newt app folder exists
  ansible.builtin.file:
    mode: "0755"
    path: "{{ newt_base_path }}"
    state: directory
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_gid'] }}"

- name: Template compose configuration
  notify: Restart newt service
  ansible.builtin.template:
    src: "templates/compose.yaml"
    dest: "{{ newt_base_path }}/compose.yaml"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
    mode: "0644"

- name: Make sure newt service is running
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    name: dc@newt
    scope: user
    enabled: true
