---
- name: Ensure Nextcloud app folder exists
  become: true
  ansible.builtin.file:
    mode: "0700"
    path: "{{ nextcloud_base_path }}"
    state: directory
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_gid'] }}"

- name: Template docker-compose configuration
  ansible.builtin.template:
    src: "templates/compose.yaml"
    dest: "{{ nextcloud_base_path }}/compose.yaml"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
    mode: "0644"
  notify: Restart nextcloud service

- name: Configure borgmatic backup for nextcloud
  when: nextcloud_backup_enabled
  tags: backup
  block:
    - name: Create borgmatic configuration for nextcloud
      become: true
      ansible.builtin.template:
        src: "templates/borgmatic-nextcloud.yaml.j2"
        dest: "{{ borgmatic_config_dir }}/nextcloud.yaml"
        owner: "root"
        group: "root"
        mode: "0600"

    - name: Initialize borg repository for nextcloud
      become: true
      ansible.builtin.shell:
        cmd: "/root/.local/bin/borgmatic --config {{ borgmatic_config_dir }}/nextcloud.yaml repo-create --encryption {{ nextcloud_backup_borgmatic_encryption_mode | default('repokey-aes-ocb') }}"
      register: borg_repo_create
      changed_when: "'repository already exists' not in borg_repo_create.stderr"
      failed_when: >
        borg_repo_create.rc != 0 and
        'repository already exists' not in borg_repo_create.stderr

- name: Make sure nextcloud service is running
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    name: dc@nextcloud
    scope: user
    enabled: true
