---
# Pangolin Zero Trust configuration variables

pangolin_base_domain: "sylvain.cloud"

# Pangolin Dashboard URL (without https://)
pangolin_dashboard_url: "pangolin.{{ pangolin_base_domain }}"

# Log level (debug, info, warning, error)
pangolin_log_level: "info"

# Let's Encrypt email for certificate generation
le_email: "{{ pangolin_le_email }}"

# SMTP configuration (values should be in secrets.sops.yaml)
smtp_user: "{{ pangolin_smtp_user }}"
smtp_pass: "{{ pangolin_smtp_pass }}"

# Pangolin secret (should be in secrets.sops.yaml)
pangolin_secret: "{{ pangolin_server_secret }}"

ufw_allowed_ports:
  - { port: "22", proto: tcp }
  - { port: "80", proto: tcp }
  - { port: "443", proto: tcp }
  - { port: "51820", proto: udp }
  - { port: "21820", proto: udp }
