---
- hosts: all
  tags: setup
  tasks:
    # WARNING : You cannot override variables with this, make sure variable is not defined before.
    # Export your age key in environment
    # https://github.com/mozilla/sops/issues/933#issuecomment-1081228720
    - name: Load secrets variable into global namespace
      tags: always
      community.sops.load_vars:
        file: "{{ playbook_dir }}/secrets.sops.yaml"
        expressions: evaluate-on-load

    - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
      become: true
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: "Install basic packages"
      become: true
      ansible.builtin.package:
        name:
          - git
          - git-lfs
          - unzip
          - htop
          - wget
          - curl
          - tmux
          - vim
          - rsync
          - jq
          - gnupg2
          - fzf
          - apt-transport-https
        state: present

    - name: Create user
      become: true
      ansible.builtin.user:
        name: "sylvain"
        shell: /bin/bash
        groups: sudo
        append: true
        password: "{{ password | password_hash('sha512') }}"
