---
collections:
  # - name: sylvainmetayer.workstation
  #   version: 1.2.67
  # - name: devsec.hardening
  #   version: 10.1.0
  - name: community.sops
    version: 2.2.4
  - name: community.general
    version: ">=8.0.0"
roles:
  - src: geerlingguy.docker
    version: 7.9.0
