---
collections:
  # - name: sylvainmetayer.workstation
  #   version: 1.2.67
  # - name: devsec.hardening
  #   version: 10.1.0
  - name: community.sops
    version: 2.2.7
  - name: community.general
    version: ">=8.0.0"
roles:
  - src: geerlingguy.docker
    version: 8.0.0
  - src: andrewrothstein.starship
    version: v1.3.0
