---

borgmatic_config_dir: "/etc/borgmatic.d"
borgmatic_encryption_mode: repokey-aes-ocb

rss_backup_enabled: true
rss_backup_borgmatic_target: "rclone:backup:{{ backup_s3_bucket_name }}/rss"
rss_backup_encryption_passphrase: "{{ backup_passphrase }}"
# TMP URL, will be deleted
rss_backup_healthcheck_url: "https://status.sylvain.cloud/api/push/01SRDYJe7RpwRvfuWulQU2ut1xFZ71RS"

betisier_backup_enabled: true
betisier_backup_borgmatic_target: "rclone:backup:{{ backup_s3_bucket_name }}/betisier"
betisier_backup_encryption_passphrase: "{{ backup_passphrase }}"

monica_v4_backup_enabled: true
monica_v4_backup_borgmatic_target: "rclone:backup:{{ backup_s3_bucket_name }}/monica_v4"
monica_v4_backup_encryption_passphrase: "{{ backup_passphrase }}"

# Wiki (Bookstack) configuration
wiki_domain: "wiki.sylvain.cloud"
wiki_backup_enabled: true
wiki_backup_borgmatic_target: "rclone:backup:{{ backup_s3_bucket_name }}/wiki"
wiki_backup_borgmatic_password: "{{ backup_passphrase }}"

# Spliit
spliit_domain: "spend.sylvain.cloud"
spliit_base_path: "{{ docker_base_path }}/spliit"
spliit_backup_borgmatic_target: "rclone:backup:{{ inventory_hostname }}/spliit"
spliit_backup_borgmatic_password: "{{ backup_passphrase }}"
